### PR TITLE
Support entertainment device interfaces

### PR DESCRIPTION
**Pull request by masachaco**
Hello, Mr.Dinh.

Alexa (for Japan) supported entertainment device interfaces at October 08, 2018.
In response to that, I thought want to make those interfaces available on alehos 3.

# Changes
I added following entertainment device interfaces support to alehos3.

- Alexa.ChannelController 
     https://developer.amazon.com/docs/device-apis/alexa-channelcontroller.html
- Alexa.Speaker 
    https://developer.amazon.com/ja/docs/device-apis/alexa-speaker.html
- Alexa.StepSpeaker 
   https://developer.amazon.com/ja/docs/device-apis/alexa-stepspeaker.html
- Alexa.PlaybackController 
    https://developer.amazon.com/ja/docs/device-apis/alexa-playbackcontroller.html
- Alexa.InputController
    https://developer.amazon.com/ja/docs/device-apis/alexa-inputcontroller.html

And I added following error response codes.
https://developer.amazon.com/docs/device-apis/alexa-errorresponse.html

- ALREADY_IN_OPERATION
- NOT_CALIBRATED
- NOT_SUPPORTED_IN_CURRENT_MODE
- NOT_IN_OPERATION
- POWER_LEVEL_NOT_SUPPORTED
- VALUE_OUT_OF_RANGE
- TEMPERATURE_VALUE_OUT_OF_RANGE

I am glad if this change is useful for the project.

Regards,
masachaco.

### CODE REVIEW

**Comment by nqd** [comment]
@masachaco thanks for the mr. Since I am no longer work with Alexa directly, please fork and I will redirect this proj to yours, or I will add you as Collaborators so that you could maintain this pkg.

**Comment by masachaco** [comment]
@nqd 
Thank you for approval. 
I was hoping to add functions in the future, so I would appreciate it if you could do that.

Regards,
masachaco.

**Comment by nqd** [comment]
@masachaco added you as a collaborator. You can now merge to master and publish to npm.

**Comment by masachaco** [comment]
@nqd 
Thank you for invitation and your kindness :)

I accepted invitation. 

Regards,
masachaco.

**Pull request merged**
